homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 166
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Moscow
  # Packages
  packages: !include_dir_named packages
  # Customization
  customize: !include_dir_merge_named customize
# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  api_password: !secret http_password
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
    - https://scontent.xx.fbcdn.net
    - https://maps.googleapis.com
    - https://materialdesignicons.com
  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
updater:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Recorder to store in MySQL
recorder: 
  db_url: !secret sql_string
  purge_days: 2
  exclude:
    domains:
      - calendar
      - updater
    entities:
      - sun.sun
      - sensor.date
      - sensor.time
      - camera.andrey_location
      - sensor.meizu_battery
      - input_select.andrey_status
      - sensor.cpu_use
      - sensor.disk_free_home
      - sensor.ha_version
      - sensor.ram_free
      - sensor.ram_use
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.to_car_commute
      - sensor.to_home_commute
      - sensor.mornig_commute
      - proximity.home
      - sensor.pws_observation_time
      - sensor.pws_pressure_trend
      - sensor.dsn24h
      - sensor.dark_sky_hourly_summary
      - sensor.ha_uptime
      - sensor.pws_wind_dir
      - sensor.home_commute
      - sensor.dark_sky_daily_summary
      - sensor.pws_solarradiation
      - sensor.pws_precip_1hr_metric
      - sensor.pws_precip_today_metric
      - sensor.work_commute
      - sensor.pws_weather
      - sensor.date_weekday
      - sensor.date_day
      - sensor.dsn7d
      - sensor.dark_sky_precip
      - sensor.pws_uv
      - sensor.ha_current_version      
      - sensor.ha_installed_version
      - sensor.pws_station_id
      - sensor.pws_location
      - sensor.pws_weather_1d_metric
      - sensor.pws_weather_1h
      - sensor.pws_weather_1n_metric
      - sensor.pws_weather_2d_metric
      - sensor.pws_weather_2h
      - sensor.pws_weather_2n_metric
      - sensor.pws_weather_3d_metric
      - sensor.pws_weather_3n_metric
      - sensor.pws_weather_4d_metric
      - sensor.pws_weather_4h
      - sensor.pws_weather_4n_metric
      - sensor.pws_weather_6h
      - sensor.pws_weather_8h
      - sensor.pushbullet_title      


# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
  exclude:  
    domains:
      - calendar
      - updater
    entities:
      - sun.sun
      - sensor.date
      - sensor.time
      - camera.andrey_location
      - sensor.meizu_battery
      - input_select.andrey_status
      - sensor.cpu_use
      - sensor.disk_free_home
      - sensor.ha_version
      - sensor.ram_free
      - sensor.ram_use
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.to_car_commute
      - sensor.to_home_commute
      - sensor.mornig_commute
      - proximity.home
      - sensor.pws_pressure_trend
      - sensor.dsn24h
      - sensor.dark_sky_hourly_summary
      - sensor.ha_uptime
      - sensor.pws_wind_dir
      - sensor.home_commute
      - sensor.dark_sky_daily_summary
      - sensor.pws_solarradiation
      - sensor.pws_precip_1hr_metric
      - sensor.pws_precip_today_metric
      - sensor.work_commute
      - sensor.pws_weather
      - sensor.date_weekday
      - sensor.date_day
      - sensor.dsn7d
      - sensor.dark_sky_precip
      - sensor.pws_uv
      - sensor.ha_current_version
      - sensor.ha_installed_version
      - sensor.pws_location
      - sensor.pws_station_id
      - sensor.pws_weather_1d_metric
      - sensor.pws_weather_1h
      - sensor.pws_weather_1n_metric
      - sensor.pws_weather_2d_metric
      - sensor.pws_weather_2h
      - sensor.pws_weather_2n_metric
      - sensor.pws_weather_3d_metric
      - sensor.pws_weather_3n_metric
      - sensor.pws_weather_4d_metric
      - sensor.pws_weather_4h
      - sensor.pws_weather_4n_metric
      - sensor.pws_weather_6h
      - sensor.pws_weather_8h
      - sensor.pushbullet_title    

# Track the sun
sun:

# Mosquitto
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: hass
  keepalive: 60
  username: !secret mqtt_usr
  password: !secret mqtt_pass
  protocol: 3.1 

# Device tracker
device_tracker: !include_dir_merge_list device_tracker

# Zones
zone: !include_dir_merge_list zones

# Proximity
proximity: !include zones/proximity.yaml
# Groups
group: !include groups.yaml

# Notifications
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key
  - name: zanzito
    platform: zanzito
    device-name: redminote3

# Xiaomi
xiaomi_aqara:  
  gateways:
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_key

# Logger
logger:
  default: warn
  logs:
#    homeassistant.components.xiaomi_aqara: debug
#    homeassistant.components.sensor.xiaomi: debug
    homeassistant.components.binary_sensor.xiaomi_aqara: debug
#    homeassistant.components.light.xiaomi: debug
#    homeassistant.components.switch.xiaomi: debug
#   homeassistant.components.light.osramlightify: debug

# Scripts
script: !include_dir_merge_named scripts/

# Automations
automation: !include_dir_merge_list automation/

# Lights
light: !include_dir_merge_list light/


#Media player
media_player:
  - platform: vlc

# Text to speech
tts:
  - platform: yandextts
    api_key: !secret yandex_key
    language: 'ru-RU'
    codec: mp3
    voice: oksana
    emotion: good
    speed: 1.0

