- alias: car_location
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.andrey_status
    from: "driving"
    to: "standby"
  action:
    - service: script.refresh_phone
    - delay: 00:00:10
    - service: mqtt.publish
      data_template:
        topic: "owntracks/bastshoes/kyron"
        payload: '{"_type":"location", "tid":"ky", "lat":{{states.device_tracker.bastshoes_MeizuPro5.attributes.latitude}}, "lon":{{ states.device_tracker.bastshoes_MeizuPro5.attributes.longitude}},"tst":{{as_timestamp(now())}},"acc":{{states.device_tracker.bastshoes_MeizuPro5.attributes.gps_accuracy}}, "conn":"m", "t":"a"}'
